// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://xhkfgjoczbllexxhgtyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhoa2Znam9jemJsbGV4eGhndHlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1NzI0NzMsImV4cCI6MjA3NzE0ODQ3M30.4lHWknTUmNoBXnhTuQF-vwgh_mzB3zkZbaOxF1XLld0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);